## Question 1:

In [64]:
import numpy as np
import gurobipy as gp
import pandas as pd

In [65]:
obj = np.array([4,5]) # objective vector
A = np.zeros((1,2)) # initialize constraint matrix
A[0,:] = [2,3] # production constraint

b = np.array([60]) # limits on production, storage, and demand
sense = np.array(['<'])

In [66]:
ojModel = gp.Model() # initialize an empty model

ojModX = ojModel.addMVar(2) # tell the model how many variables there are
# must define the variables before adding constraints because variables go into the constraints
ojModCon = ojModel.addMConstrs(A, ojModX, sense, b) # add the constraints to the model
ojModel.setMObjective(None,obj,0,sense=gp.GRB.MAXIMIZE) # add the objective to the model...we'll talk about the None and the 0

ojModel.Params.OutputFlag = 0 # tell gurobi to shut up!!

In [67]:
ojModel.optimize()

In [68]:
ojModel.objVal

120.0

In [69]:
ojModX.x

array([30.,  0.])

In [70]:
obj = np.array([4,5]) # objective vector
A = np.zeros((2,2)) # initialize constraint matrix
A[0,:] = [2,3] # production constraint
A[1,:] = [1,-1]
b = np.array([60,0]) # limits on production, storage, and demand
sense = np.array(['<','<'])

In [71]:
ojModel = gp.Model() # initialize an empty model

ojModX = ojModel.addMVar(2) # tell the model how many variables there are
# must define the variables before adding constraints because variables go into the constraints
ojModCon = ojModel.addMConstrs(A, ojModX, sense, b) # add the constraints to the model
ojModel.setMObjective(None,obj,0,sense=gp.GRB.MAXIMIZE) # add the objective to the model...we'll talk about the None and the 0

ojModel.Params.OutputFlag = 0 # tell gurobi to shut up!!

In [72]:
ojModel.optimize()
ojModel.objVal

108.0

In [73]:
ojModX.x

array([12., 12.])

In [74]:
#Decrease in points:

120-108

12

## Question 2:

In [75]:
obj = np.array([2000,3000]) # objective vector
A = np.zeros((3,2)) # initialize constraint matrix
A[0,:] = [3,2] # workers constraint
A[1,:] = [2,4] # fertilizer constraint
A[2,:] = [1,1] # area constraint

b = np.array([1000,1200,450]) # limits on production, storage, and demand
sense = np.array(['<','<','<'])

In [76]:
ojModel = gp.Model() # initialize an empty model

ojModX = ojModel.addMVar(2) # tell the model how many variables there are
# must define the variables before adding constraints because variables go into the constraints
ojModCon = ojModel.addMConstrs(A, ojModX, sense, b) # add the constraints to the model
ojModel.setMObjective(None,obj,0,sense=gp.GRB.MAXIMIZE) # add the objective to the model...we'll talk about the None and the 0

ojModel.Params.OutputFlag = 0 # tell gurobi to shut up!!

In [77]:
ojModel.optimize()

In [78]:
ojModel.objVal

1000000.0

In [79]:
ojModX.x

array([200., 200.])

In [80]:
#When the availability of fertilizer varies from 200 tons to 2200 tons in 100-ton increments:

profit = []
wc = []

for i in range(200,2201,100):
    obj = np.array([2000,3000]) # objective vector
    A = np.zeros((3,2)) # initialize constraint matrix
    A[0,:] = [3,2] # workers constraint
    A[1,:] = [2,4] # fertilizer constraint
    A[2,:] = [1,1] # area constraint

    b = np.array([1000,i,450]) # limits on production, storage, and demand
    sense = np.array(['<','<','<'])
    
    ojModel = gp.Model() # initialize an empty model

    ojModX = ojModel.addMVar(2) # tell the model how many variables there are
    # must define the variables before adding constraints because variables go into the constraints
    ojModCon = ojModel.addMConstrs(A, ojModX, sense, b) # add the constraints to the model
    ojModel.setMObjective(None,obj,0,sense=gp.GRB.MAXIMIZE) # add the objective to the model...we'll talk about the None and the 0

    ojModel.Params.OutputFlag = 0 # tell gurobi to shut up!!
    
    ojModel.optimize()
    
    profit.append(ojModel.objVal)
    
    wc.append(ojModX.x)

In [81]:
table = pd.DataFrame(wc, columns = ['Wheat','Corn'])
table['fertilizers'] = range(200,2201,100)
table['profits'] = profit

In [82]:
table

Wheat   Corn  fertilizers    profits
0   100.0    0.0          200   200000.0
1   150.0    0.0          300   300000.0
2   200.0    0.0          400   400000.0
3   250.0    0.0          500   500000.0
4   300.0    0.0          600   600000.0
5   325.0   12.5          700   687500.0
6   300.0   50.0          800   750000.0
7   275.0   87.5          900   812500.0
8   250.0  125.0         1000   875000.0
9   225.0  162.5         1100   937500.0
10  200.0  200.0         1200  1000000.0
11  175.0  237.5         1300  1062500.0
12  150.0  275.0         1400  1125000.0
13  125.0  312.5         1500  1187500.0
14  100.0  350.0         1600  1250000.0
15   50.0  400.0         1700  1300000.0
16    0.0  450.0         1800  1350000.0
17    0.0  450.0         1900  1350000.0
18    0.0  450.0         2000  1350000.0
19    0.0  450.0         2100  1350000.0
20    0.0  450.0         2200  1350000.0

## Question 3:

In [177]:
obj = np.array([13,16,16,14,39]) # objective vector

A = np.zeros((7,5)) # initialize constraint matrix

A[0,:] = [11,53,5,5,29] # corn serving constraint
A[1,:] = [3,6,5,1,34] # milk constraint
A[2,:] = [1,0,0,0,0] # bread constraint
A[3,:] = [0,1,0,0,0] # vitamin constraint
A[4,:] = [0,0,1,0,0] # calories constraint
A[5,:] = [0,0,0,1,0] # vitamin constraint
A[6,:] = [0,0,0,0,1] # vitamin constraint


b = np.array([40,20,1,1,1,1,1]) # limits on production, storage, and demand
sense = np.array(['<','<','<','<','<','<','<'])


ojModel = gp.Model() # initialize an empty model

ojModX = ojModel.addMVar(5) # tell the model how many variables there are
# must define the variables before adding constraints because variables go into the constraints
ojModCon = ojModel.addMConstrs(A, ojModX, sense, b) # add the constraints to the model
ojModel.setMObjective(None,obj,0,sense=gp.GRB.MAXIMIZE) # add the objective to the model
ojModel.Params.OutputFlag = 0 # tell gurobi to shut up!!

In [178]:
ojModel.optimize()

In [179]:
ojModel.objVal

57.449017199017206

In [180]:
ojModX.x

array([1.        , 0.20085995, 1.        , 1.        , 0.28808354])

## Question 4:

In [166]:
obj = np.array([0.18,0.23,0.05]) # objective vector

A = np.zeros((7,3)) # initialize constraint matrix

A[0,:] = [1,0,0] # corn serving constraint
A[1,:] = [0,1,0] # milk constraint
A[2,:] = [0,0,1] # bread constraint
A[3,:] = [72,121,65] # vitamin constraint

A[4,:] = [107,500,0] # calories constraint

A[5,:] = [72,121,65] # vitamin constraint

A[6,:] = [107,500,0] # vitamin constraint


b = np.array([10,10,10,2250,50000,2000,5000]) # limits on production, storage, and demand
sense = np.array(['<','<','<','<','<','>','>'])


ojModel = gp.Model() # initialize an empty model

ojModX = ojModel.addMVar(3) # tell the model how many variables there are
# must define the variables before adding constraints because variables go into the constraints
ojModCon = ojModel.addMConstrs(A, ojModX, sense, b) # add the constraints to the model
ojModel.setMObjective(None,obj,0,sense=gp.GRB.MINIMIZE) # add the objective to the model
ojModel.Params.OutputFlag = 0 # tell gurobi to shut up!!

In [167]:
ojModel.optimize()

In [168]:
ojModel.objVal

3.1500000000000004

In [169]:
ojModX.x

array([ 1.94444444, 10.        , 10.        ])

## Question 5:

In [171]:
obj = np.array([1,1.3,1.4,1,1.2,1.6]) # objective vector

A = np.zeros((8,6)) # initialize constraint matrix

A[0,:] = [1,1,1,0,0,0] # Unit 1 acre constraint
A[1,:] = [0,0,0,1,1,1] # Unit 2 acre constraint
A[2,:] = [1,0,0,1,0,0] # Year 1 wood constraint
A[3,:] = [0,1.3,0,0,1.2,0] # Year 2 wood constraint
A[4,:] = [0,0,1.4,0,0,1.6] # Year 3 wood constraint
A[5,:] = [1,0,0,1,0,0] # Year 1 wood constraint
A[6,:] = [0,1.3,0,0,1.2,0] # Year 2 wood constraint
A[7,:] = [0,0,1.4,0,0,1.6] # Year 3 wood constraint



b = np.array([2,3,2,2,3,1.2,1.5,2]) # limits on production, storage, and demand
sense = np.array(['<','<','<','<','<','>','>','>'])


ojModel = gp.Model() # initialize an empty model

ojModX = ojModel.addMVar(6) # tell the model how many variables there are
# must define the variables before adding constraints because variables go into the constraints
ojModCon = ojModel.addMConstrs(A, ojModX, sense, b) # add the constraints to the model
ojModel.setMObjective(None,obj,0,sense=gp.GRB.MAXIMIZE) # add the objective to the model

ojModel.Params.OutputFlag = 0 # tell gurobi to shut up!!



In [172]:
ojModel.optimize()

In [173]:
ojModel.objVal

6.586538461538462

In [174]:
ojModX.x

array([0.46153846, 1.53846154, 0.        , 1.125     , 0.        ,
       1.875     ])