### Question 1

#### Equations :

f = first mortgage

s = second mortgage

h = home improvement

p = personal overdraft

**f + s + h + p = 250 -- (1)**

f = 0.55(f + s)

**0.45f - 0.55s = 0 -- (2)**

s = 0.25(f+s+h+p)

s = 0.25(250)

**s-62.5 -- (3)**


**0.14f + 0.2s + 0.2h + 0.1p = 37.5 -- (4)**





In [2]:
import numpy as np

In [3]:
A = np.array([[1,1,1,1],[0,1,0,0],[0.45,-0.55,0,0],[0.14,0.2,0.2,0.1]])

In [4]:
b = [250,62.5,0,37.5]

In [5]:
x = np.linalg.solve(A,b)
x


array([76.38888889, 62.5       , 31.94444444, 79.16666667])

In [6]:
x[2]

31.944444444444425

### Question 2

In [7]:
X = np.array([[1,-1,0,0,0],[1,0,-1,0,0],[1,0,0,-1,0],[1,0,0,0,-1],[0,1,-1,0,0],[0,1,0,-1,0],[0,1,0,0,-1],[0,0,1,-1,0],[0,0,1,0,-1],[0,0,0,1,-1]])

In [8]:
X

array([[ 1, -1,  0,  0,  0],
       [ 1,  0, -1,  0,  0],
       [ 1,  0,  0, -1,  0],
       [ 1,  0,  0,  0, -1],
       [ 0,  1, -1,  0,  0],
       [ 0,  1,  0, -1,  0],
       [ 0,  1,  0,  0, -1],
       [ 0,  0,  1, -1,  0],
       [ 0,  0,  1,  0, -1],
       [ 0,  0,  0,  1, -1]])

In [9]:
Y = np.array([-45,-3,-31,-45,18,8,20,2,-27,-38])
Y

array([-45,  -3, -31, -45,  18,   8,  20,   2, -27, -38])

In [10]:
X_transpose = X.T
X_transpose

array([[ 1,  1,  1,  1,  0,  0,  0,  0,  0,  0],
       [-1,  0,  0,  0,  1,  1,  1,  0,  0,  0],
       [ 0, -1,  0,  0, -1,  0,  0,  1,  1,  0],
       [ 0,  0, -1,  0,  0, -1,  0, -1,  0,  1],
       [ 0,  0,  0, -1,  0,  0, -1,  0, -1, -1]])

In [11]:
M = X_transpose@X
M

array([[ 4, -1, -1, -1, -1],
       [-1,  4, -1, -1, -1],
       [-1, -1,  4, -1, -1],
       [-1, -1, -1,  4, -1],
       [-1, -1, -1, -1,  4]])

In [12]:
p = X_transpose@Y
p

array([-124,   91,  -40,  -17,   90])

In [13]:
M[4:] = [1,1,1,1,1]
M

array([[ 4, -1, -1, -1, -1],
       [-1,  4, -1, -1, -1],
       [-1, -1,  4, -1, -1],
       [-1, -1, -1,  4, -1],
       [ 1,  1,  1,  1,  1]])

In [14]:
p[4:] = [0]
p

array([-124,   91,  -40,  -17,    0])

In [15]:
r = np.linalg.solve(M,p)
r

array([-24.8,  18.2,  -8. ,  -3.4,  18. ])

In [16]:
def rankof(A):
 
    R = []
 
    for i in range(len(A)):
        r = 1
        for j in range(len(A)):
            if j != i and A[j] > A[i]:
                r = r+1     
    
        R.append(r) 
        
    return R

rankof(r)



#R = [0 for x in range(len(A))]

[5, 1, 4, 3, 2]

### Question 3

In [17]:
matrix_4 = np.zeros((4,4))
print(matrix_4)

matrix_20 = np.zeros((20,20))
print(matrix_20)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0

In [18]:
for i in range(4):
    for j in range(4):
        if j>i:
            matrix_4[i,j] = (i+1)/(j+1)
        else:
            matrix_4[i,j] = (j+1)/(i+1)
            
matrix_4

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.5       , 1.        , 0.66666667, 0.5       ],
       [0.33333333, 0.66666667, 1.        , 0.75      ],
       [0.25      , 0.5       , 0.75      , 1.        ]])

In [19]:
for i in range(20):
    for j in range(20):
        if j>i:
            matrix_20[i,j] = (i+1)/(j+1)
        else:
            matrix_20[i,j] = (j+1)/(i+1)
            
matrix_20.T == matrix_20

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True],
       [ T

### Question 4

In [20]:
C = np.linalg.inv(matrix_20)
C

array([[ 1.33333333e+00, -6.66666667e-01,  0.00000000e+00,
        -1.79750394e-16,  1.11022302e-16,  2.35501854e-17,
         4.41242484e-17,  7.40148683e-17, -3.70074342e-17,
         1.48029737e-16, -2.33499287e-16,  5.30976229e-17,
        -2.88657986e-17,  7.40148683e-17,  7.40148683e-17,
        -1.09828514e-16, -2.46519033e-31,  1.14458707e-16,
         7.40148683e-17,  1.23259516e-31],
       [-6.66666667e-01,  2.13333333e+00, -1.20000000e+00,
         2.96059473e-16, -6.26659218e-16,  3.40468394e-16,
        -1.95854728e-16,  1.18423789e-16,  2.04629342e-16,
        -3.40468394e-16,  1.83627364e-16,  2.18182960e-16,
         2.20268248e-16, -2.22866992e-16,  2.07241631e-16,
        -1.72860531e-16,  3.98334564e-16, -3.30106313e-16,
         1.18423789e-16, -1.33226763e-16],
       [-7.51820163e-33, -1.20000000e+00,  3.08571429e+00,
        -1.71428571e+00,  1.27305573e-15, -1.00093094e-15,
         4.67025686e-16, -2.98174184e-16, -2.43502697e-16,
         3.34569465e-16,  7.3

In [21]:
A = matrix_20
C = np.linalg.inv(A)
C


array([[ 1.33333333e+00, -6.66666667e-01,  0.00000000e+00,
        -1.79750394e-16,  1.11022302e-16,  2.35501854e-17,
         4.41242484e-17,  7.40148683e-17, -3.70074342e-17,
         1.48029737e-16, -2.33499287e-16,  5.30976229e-17,
        -2.88657986e-17,  7.40148683e-17,  7.40148683e-17,
        -1.09828514e-16, -2.46519033e-31,  1.14458707e-16,
         7.40148683e-17,  1.23259516e-31],
       [-6.66666667e-01,  2.13333333e+00, -1.20000000e+00,
         2.96059473e-16, -6.26659218e-16,  3.40468394e-16,
        -1.95854728e-16,  1.18423789e-16,  2.04629342e-16,
        -3.40468394e-16,  1.83627364e-16,  2.18182960e-16,
         2.20268248e-16, -2.22866992e-16,  2.07241631e-16,
        -1.72860531e-16,  3.98334564e-16, -3.30106313e-16,
         1.18423789e-16, -1.33226763e-16],
       [-7.51820163e-33, -1.20000000e+00,  3.08571429e+00,
        -1.71428571e+00,  1.27305573e-15, -1.00093094e-15,
         4.67025686e-16, -2.98174184e-16, -2.43502697e-16,
         3.34569465e-16,  7.3

In [22]:
d = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [23]:
x = np.linalg.solve(A,(C@d))
x

array([-8.88178420e-16,  9.94759830e-15,  3.52070682e-15, -7.26913457e-14,
        1.59424384e-13, -2.54373524e-13,  2.73454074e-13, -1.12927026e-13,
       -2.48120301e+01,  2.00642393e+01,  3.58137507e+01, -3.00626280e+01,
       -3.73699569e-04, -2.77204400e-04, -2.09968770e-04, -1.61954093e-04,
       -1.26922825e-04, -1.00877939e-04,  9.50593309e+01, -1.00062903e+02])

In [24]:
x[9]

20.064239273130674

In [2]:
import numpy as np

In [7]:
A=np.zeros((4,4))

In [8]:
A

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
for i in range(4):
    for j in range(4):
        if i < j:
            A[i,j] = (i+1)/(j+1)
        else:
            A[i,j] = (i+1)/(j+1)
A
        

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [2.        , 1.        , 0.66666667, 0.5       ],
       [3.        , 1.5       , 1.        , 0.75      ],
       [4.        , 2.        , 1.33333333, 1.        ]])