In [3]:
import numpy as np
import gurobipy as gp

### Question 2:

In [4]:
obj = np.array([9,5,6,4])
A = np.zeros((3,4))
A[0,:] = [6,3,5,2]
A[1,:] = [0,0,1,1]
A[2,:] = [1,1,0,0]
sense = ['<','<','>']
b = np.array([11,1,1])

In [5]:
ipMod = gp.Model()
ipMod_x = ipMod.addMVar(4,vtype=['B']*4) # 'C' or 'I' or 'B'
ipMod_con = ipMod.addMConstrs(A, ipMod_x, sense, b)
ipMod.setMObjective(None,obj,0,sense=gp.GRB.MAXIMIZE)

ipMod.Params.OutputFlag = 0 # tell gurobi to shut up!!
ipMod.optimize()

Restricted license - for non-production use only - expires 2022-01-13


In [6]:
ipMod_x.x

array([1., 1., 0., 1.])

### Question 3:

In [11]:
obj = np.array([1]*12)

In [12]:
A = np.zeros((11,12))
A[0,:] = [0,0,1,0,1,0,1,1,1,0,0,0]
A[1,:] = [0,0,0,0,0,0,0,1,1,0,0,0]
A[2,:] = [1,0,0,0,0,0,1,1,1,0,0,0]
A[3,:] = [0,0,0,0,0,0,0,0,0,1,0,0]
A[4,:] = [1,1,0,0,0,0,0,0,0,0,0,0]
A[5,:] = [0,0,0,0,0,0,0,0,0,1,1,0]
A[6,:] = [1,0,1,0,1,0,0,0,0,0,0,0]
A[7,:] = [1,1,1,0,0,0,0,0,1,0,0,0]
A[8,:] = [1,1,1,0,0,0,0,1,0,0,0,0]
A[9,:] = [0,0,0,1,0,1,0,0,0,0,1,1]
A[10,:]= [0,0,0,0,0,1,0,0,0,1,0,1]

sense = ['>']*11
b = np.array([1]*11)

In [13]:
ipMod = gp.Model()
ipMod_x = ipMod.addMVar(12,vtype=['B']*12) # 'C' or 'I' or 'B'
ipMod_con = ipMod.addMConstrs(A, ipMod_x, sense, b)
ipMod.setMObjective(None,obj,0,sense=gp.GRB.MINIMIZE)

ipMod.Params.OutputFlag = 0 # tell gurobi to shut up!!
ipMod.optimize()

In [14]:
ipMod_x.x

array([1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1.])

### Question 4:

In [76]:
obj = np.array([20,8,16,4,9,12,21])

In [77]:
A = np.zeros((3,7))
A[0,:] = [4,3,2,1,0,0,1]
A[1,:] = [0,1,0,1,3,0,2]
A[2,:] = [0,0,1,1,0,2,0]

sense = ['>','>','>']
b = np.array([233,148,106])

In [78]:
ipMod = gp.Model()
ipMod_x = ipMod.addMVar(7,vtype=['I']*7) # 'C' or 'I' or 'B'
ipMod_con = ipMod.addMConstrs(A, ipMod_x, sense, b)
ipMod.setMObjective(None,obj,0,sense=gp.GRB.MINIMIZE)

ipMod.Params.OutputFlag = 0 # tell gurobi to shut up!!
ipMod.optimize()

In [79]:
ipMod_x.x

array([  0.,  42.,  -0., 107.,  -0.,  -0.,  -0.])

In [80]:
ipMod.objVal

764.0

### Question 5:

In [62]:
obj = np.array([330, 300, 330, 360, 360, 360, 360])

In [63]:
A = np.zeros((7,7))
A[0,:] = [1,0,0,1,1,1,1]
A[1,:] = [1,1,0,0,1,1,1]
A[2,:] = [1,1,1,0,0,1,1]
A[3,:] = [1,1,1,1,0,0,1]
A[4,:] = [1,1,1,1,1,0,0]
A[5,:] = [0,1,1,1,1,1,0]
A[6,:] = [0,0,1,1,1,1,1]


sense = ['>']*7
b = np.array([5,13,12,10,14,8,6])

In [64]:
ipMod = gp.Model()
ipMod_x = ipMod.addMVar(7,vtype=['I']*7) # 'C' or 'I' or 'B'
ipMod_con = ipMod.addMConstrs(A, ipMod_x, sense, b)
ipMod.setMObjective(None,obj,0,sense=gp.GRB.MINIMIZE)

ipMod.Params.OutputFlag = 0 # tell gurobi to shut up!!
ipMod.optimize()

In [65]:
ipMod_x.x

array([ 1.,  8.,  2., -0.,  3.,  1., -0.])